In [138]:
import numpy as np

In [139]:
X=np.array([[1,1],[2,2],[3,3],[4,4],[5,5]])
y=np.array([1,2,3,4,5])

## Two Methords of implementing Linear Regression

1. Iterative methord
2. Closed form solution

### Closed Form Solution:-
#### Linear Algebra approach
Ax=B
linear combination of A should be as close as possible to B, if B in space of A then solution is possible simply by solving x for Ax=B, else need to find the closest space of B that is in column space of A
and that closest space is when B is projected onto column space of A  <br>
Ax=PB (projecting B into A's subspace)<br>
Ax=A(ATA)-1ATB <br>
so X=(ATA)-1ATB <br>

#### Calculus approach:
find minima by using dl/dw=0 where L= mean squared loss= (y-wx)T(y-wx)

#### probability/statistics approach (MLE)
y=wx+E where E is assumed to be a gaussian noise So inorder to have minimum noise we need to best approximate the parameter w
so maximum likely hood estimate of normal curve will finally lead to minimization of (y-wx)^2 (mean squared loss)



In [140]:
# add 1 to get intercept term
X=np.append(X,axis=1,values=[[1],[1],[1],[1],[1]])
print(X)

[[1 1 1]
 [2 2 1]
 [3 3 1]
 [4 4 1]
 [5 5 1]]


In [141]:
W=np.linalg.pinv(X.T@X)@(X.T@y)  #pinv is pseudo inverse
print(W)

[0.5 0.5 0. ]


In [142]:
pred=W@np.array([6,6,1])
print(pred)

5.999999999999997


## iterative solution
dw=(dL/dw)   L=loss function (y-ypred)^2/n (mean squared error) <br>
dl/dw=(2/n)*(y-ypred).X 


In [150]:
import numpy as np

# Inputs
X = np.array([[1, 1],
              [2, 2],
              [3, 3],
              [4, 4],
              [5, 5]])
y = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # shape (5, 1)

# Add intercept (bias) term to X
X = np.hstack([X, np.ones((X.shape[0], 1))])  # shape (5, 3)

# Initialize weights (2 features + 1 bias)
W = np.zeros((X.shape[1], 1))  # shape (3, 1)

# Hyperparameters
lr = 0.01
epochs = 1000
n = X.shape[0]

# Gradient Descent Loop
for i in range(epochs):
    y_pred = X @ W
    error = y_pred - y

    gradients = (2/n) * (X.T @ error)
    W -= lr * gradients

    if i % 100 == 0:
        loss = np.mean(error ** 2)
        print(f"Epoch {i}: Loss = {loss:.4f}")

# Output
print("\nFinal Parameters (theta):", W)
print("Predictions:", (X @ W))



Epoch 0: Loss = 11.0000
Epoch 100: Loss = 0.0016
Epoch 200: Loss = 0.0008
Epoch 300: Loss = 0.0004
Epoch 400: Loss = 0.0002
Epoch 500: Loss = 0.0001
Epoch 600: Loss = 0.0000
Epoch 700: Loss = 0.0000
Epoch 800: Loss = 0.0000
Epoch 900: Loss = 0.0000

Final Parameters (theta): [[0.49945628]
 [0.49945628]
 [0.0039555 ]]
Predictions: [[1.00286806]
 [2.00178063]
 [3.00069319]
 [3.99960576]
 [4.99851833]]
